version: '3.8'
services:
  mysql:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: change-me
      MYSQL_DATABASE: mininews
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mininews

  mininews:
    image: openjdk:20-jdk
    volumes:
      - ../target/mini-news-1.0-SNAPSHOT.jar:/mini-news-1.0-SNAPSHOT.jar
    depends_on:
      - mysql
    ports:
      - '8080:8080'
      - '5005:5005'
    networks:
      - mininews
    stdin_open: true
    tty: true
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar mini-news-1.0-SNAPSHOT.jar

networks:
  mininews:
    driver: bridge
